import 'package:flutter/material.dart';

var gridData = [
  "HOME",
  "MAIL",
  "PHONE",
  "CAMERA",
  "BACKUP",
  "ACCOUNT",
  "PICTURE",
  "TRASH",
  "SEND",
  "SEARCH",
  "VIDEO",
  "MUTE",
  "HEADSET",
  "VOLUME"
];
var gridIcons = [
  Icon(Icons.home),
  Icon(Icons.mail),
  Icon(Icons.phone),
  Icon(Icons.camera_alt_outlined),
  Icon(Icons.backup_outlined),
  Icon(Icons.account_circle),
  Icon(Icons.image),
  Icon(Icons.delete),
  Icon(Icons.send),
  Icon(Icons.search),
  Icon(Icons.video_call),
  Icon(Icons.mic_off),
  Icon(Icons.headphones),
  Icon(Icons.volume_down),
];
var cardColors = [
  Colors.purpleAccent,
  Colors.orange,
  Colors.lightGreenAccent,
  Colors.greenAccent,
  Colors.limeAccent,
  Colors.white60,
  Colors.lightBlueAccent,
  Colors.pink,
  Colors.indigo,
  Colors.deepOrange,
  Colors.teal,
  Colors.green,
  Colors.purple,
  Colors.lightBlueAccent,
];
